#!/usr/bin/zsh

setopt promptsubst

git_status() {
  if git rev-parse --git-dir > /dev/null 2>&1; then
    local git_branch
    git_branch=$(git branch --show-current 2>/dev/null)
    local staged_changes
    staged_changes=$(git diff --cached --name-only | wc -l)
    local unstaged_changes
    unstaged_changes=$(git diff --name-only | wc -l)
    local untracked_changes
    untracked_changes=$(git ls-files --others --exclude-standard | wc -l)
    local git_empty
    git_empty=$(git rev-parse --quiet --verify HEAD 2>/dev/null)

    if [ -z "$git_empty" ]; then
      if [ "$untracked_changes" -gt 0 ]; then
        git_color="%{\033[1;31m%}"
      elif [ "$staged_changes" -gt 0 ]; then
        git_color="%{\033[1;33m%}"
      else
        git_color="%{\033[1;32m%}"
      fi
    else
      if [ "$unstaged_changes" -gt 0 ] || [ "$untracked_changes" -gt 0 ]; then
        git_color="%{\033[1;31m%}"
      elif [ "$staged_changes" -gt 0 ] && [ "$unstaged_changes" -eq 0 ] && [ "$untracked_changes" -eq 0 ]; then
        git_color="%{\033[1;33m%}"
      else
        git_color="%{\033[1;32m%}"
      fi
    fi
    echo "${git_color}${git_branch}%{\033[0m%} "
  fi
}

PS1=$'%{\033[1;34m%}%1/%{\033[0m%} \$(git_status)%# '
